# cache-bust: 2026-08-18-fb-pixel-build-arg
FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG NEXT_PUBLIC_WP_URL
ARG NEXT_PUBLIC_STORE_API_URL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_GTM_ID
ARG NEXT_PUBLIC_WHATSAPP_NUMBER
ARG NEXT_PUBLIC_WHATSAPP_GENERAL
ARG NEXT_PUBLIC_FB_PIXEL_ID
ARG NEXT_PUBLIC_MP_PUBLIC_KEY
ARG BREVO_API_KEY
ARG BREVO_NEWSLETTER_LIST_ID
ARG BREVO_ABANDONED_CART_LIST_ID
ARG BREVO_BIRTHDAY_LIST_ID
ARG WP_URL
ARG REVALIDATION_SECRET
ARG AUTH_SECRET
ARG WC_API_AUTH
ARG GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG MERCADOPAGO_ACCESS_TOKEN

ENV NEXT_PUBLIC_WP_URL=$NEXT_PUBLIC_WP_URL
ENV NEXT_PUBLIC_STORE_API_URL=$NEXT_PUBLIC_STORE_API_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_GTM_ID=$NEXT_PUBLIC_GTM_ID
ENV NEXT_PUBLIC_WHATSAPP_NUMBER=$NEXT_PUBLIC_WHATSAPP_NUMBER
ENV NEXT_PUBLIC_WHATSAPP_GENERAL=$NEXT_PUBLIC_WHATSAPP_GENERAL
ENV NEXT_PUBLIC_FB_PIXEL_ID=$NEXT_PUBLIC_FB_PIXEL_ID
ENV NEXT_PUBLIC_MP_PUBLIC_KEY=$NEXT_PUBLIC_MP_PUBLIC_KEY
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV BREVO_API_KEY=$BREVO_API_KEY
ENV BREVO_NEWSLETTER_LIST_ID=$BREVO_NEWSLETTER_LIST_ID
ENV BREVO_ABANDONED_CART_LIST_ID=$BREVO_ABANDONED_CART_LIST_ID
ENV BREVO_BIRTHDAY_LIST_ID=$BREVO_BIRTHDAY_LIST_ID
ENV WP_URL=$WP_URL
ENV REVALIDATION_SECRET=$REVALIDATION_SECRET
ENV AUTH_SECRET=$AUTH_SECRET
ENV WC_API_AUTH=$WC_API_AUTH
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV MERCADOPAGO_ACCESS_TOKEN=$MERCADOPAGO_ACCESS_TOKEN

RUN npm run build

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
RUN chown -R nextjs:nodejs /app

USER nextjs

ENV PORT=3000
ENV HOSTNAME=0.0.0.0
EXPOSE 3000
CMD ["npm", "start"]
