FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG NEXT_PUBLIC_WP_URL
ARG NEXT_PUBLIC_STORE_API_URL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_GTM_ID
ARG NEXT_PUBLIC_WHATSAPP_NUMBER
ARG NEXT_PUBLIC_MP_PUBLIC_KEY
ARG BREVO_API_KEY
ARG BREVO_NEWSLETTER_LIST_ID
ARG BREVO_ABANDONED_CART_LIST_ID
ARG WP_URL
ARG REVALIDATION_SECRET

ENV NEXT_PUBLIC_WP_URL=$NEXT_PUBLIC_WP_URL
ENV NEXT_PUBLIC_STORE_API_URL=$NEXT_PUBLIC_STORE_API_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_GTM_ID=$NEXT_PUBLIC_GTM_ID
ENV NEXT_PUBLIC_WHATSAPP_NUMBER=$NEXT_PUBLIC_WHATSAPP_NUMBER
ENV NEXT_PUBLIC_MP_PUBLIC_KEY=$NEXT_PUBLIC_MP_PUBLIC_KEY
ENV BREVO_API_KEY=$BREVO_API_KEY
ENV BREVO_NEWSLETTER_LIST_ID=$BREVO_NEWSLETTER_LIST_ID
ENV BREVO_ABANDONED_CART_LIST_ID=$BREVO_ABANDONED_CART_LIST_ID
ENV WP_URL=$WP_URL
ENV REVALIDATION_SECRET=$REVALIDATION_SECRET

RUN npm run build

ENV PORT=3000
ENV HOSTNAME=0.0.0.0
EXPOSE 3000
CMD ["npm", "start"]
